import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Slider, WelcomeBack } from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.slider_wrapper}>
          <Slider />
        </div>

        <div className={styles.welcome_back}>
          <WelcomeBack />
        </div>

      </main>
    </>
  )
}
