import Head from "next/head";
import React from "react";

interface HeaderProps {
  title: string;
}
export default function Header({ title }: HeaderProps) {
  return (
    <Head>
      <title>{title} | Viran</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
